# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capk_globals.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='capk_globals.proto',
  package='capkproto',
  serialized_pb='\n\x12\x63\x61pk_globals.proto\x12\tcapkproto*\x1a\n\x06side_t\x12\x07\n\x03\x42ID\x10\x01\x12\x07\n\x03\x41SK\x10\x02*\x1e\n\nord_type_t\x12\x07\n\x03MKT\x10\x01\x12\x07\n\x03LIM\x10\x02*P\n\x0ftime_in_force_t\x12\x07\n\x03GFD\x10\x00\x12\x07\n\x03GTC\x10\x01\x12\x07\n\x03OPG\x10\x02\x12\x07\n\x03IOC\x10\x03\x12\x07\n\x03\x46OK\x10\x04\x12\x07\n\x03GTX\x10\x05\x12\x07\n\x03GTD\x10\x06')

_SIDE_T = _descriptor.EnumDescriptor(
  name='side_t',
  full_name='capkproto.side_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BID', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASK', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=33,
  serialized_end=59,
)

side_t = enum_type_wrapper.EnumTypeWrapper(_SIDE_T)
_ORD_TYPE_T = _descriptor.EnumDescriptor(
  name='ord_type_t',
  full_name='capkproto.ord_type_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MKT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIM', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=61,
  serialized_end=91,
)

ord_type_t = enum_type_wrapper.EnumTypeWrapper(_ORD_TYPE_T)
_TIME_IN_FORCE_T = _descriptor.EnumDescriptor(
  name='time_in_force_t',
  full_name='capkproto.time_in_force_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GFD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GTC', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPG', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IOC', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FOK', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GTX', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GTD', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=93,
  serialized_end=173,
)

time_in_force_t = enum_type_wrapper.EnumTypeWrapper(_TIME_IN_FORCE_T)
BID = 1
ASK = 2
MKT = 1
LIM = 2
GFD = 0
GTC = 1
OPG = 2
IOC = 3
FOK = 4
GTX = 5
GTD = 6




# @@protoc_insertion_point(module_scope)
