# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution_ack.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import capk_globals_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='execution_ack.proto',
  package='capkproto',
  serialized_pb='\n\x13\x65xecution_ack.proto\x12\tcapkproto\x1a\x12\x63\x61pk_globals.proto\"\x8a\x02\n\rexecution_ack\x12\x10\n\x08order_id\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63l_order_id\x18\x02 \x01(\x0c\x12\x17\n\x0f\x65xec_ack_status\x18\x03 \x01(\x0f\x12\x0f\n\x07\x65xec_id\x18\x04 \x01(\x0c\x12\x0e\n\x06symbol\x18\x05 \x01(\t\x12\x15\n\rfut_sett_date\x18\x06 \x01(\t\x12\x1f\n\x04side\x18\x07 \x01(\x0e\x32\x11.capkproto.side_t\x12\x11\n\torder_qty\x18\x08 \x01(\x01\x12\x10\n\x08last_qty\x18\t \x01(\x01\x12\x12\n\nlast_price\x18\n \x01(\x01\x12\x0f\n\x07\x63um_qty\x18\x0b \x01(\x01\x12\x16\n\x0elast_spot_rate\x18\x0c \x01(\x01')




_EXECUTION_ACK = _descriptor.Descriptor(
  name='execution_ack',
  full_name='capkproto.execution_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='capkproto.execution_ack.order_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cl_order_id', full_name='capkproto.execution_ack.cl_order_id', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exec_ack_status', full_name='capkproto.execution_ack.exec_ack_status', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exec_id', full_name='capkproto.execution_ack.exec_id', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='capkproto.execution_ack.symbol', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fut_sett_date', full_name='capkproto.execution_ack.fut_sett_date', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='side', full_name='capkproto.execution_ack.side', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order_qty', full_name='capkproto.execution_ack.order_qty', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_qty', full_name='capkproto.execution_ack.last_qty', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_price', full_name='capkproto.execution_ack.last_price', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cum_qty', full_name='capkproto.execution_ack.cum_qty', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_spot_rate', full_name='capkproto.execution_ack.last_spot_rate', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=321,
)

_EXECUTION_ACK.fields_by_name['side'].enum_type = capk_globals_pb2._SIDE_T
DESCRIPTOR.message_types_by_name['execution_ack'] = _EXECUTION_ACK

class execution_ack(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECUTION_ACK

  # @@protoc_insertion_point(class_scope:capkproto.execution_ack)


# @@protoc_insertion_point(module_scope)
