// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: execution_ack.proto

#ifndef PROTOBUF_execution_5fack_2eproto__INCLUDED
#define PROTOBUF_execution_5fack_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "capk_globals.pb.h"
// @@protoc_insertion_point(includes)

namespace capkproto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_execution_5fack_2eproto();
void protobuf_AssignDesc_execution_5fack_2eproto();
void protobuf_ShutdownFile_execution_5fack_2eproto();

class execution_ack;

// ===================================================================

class execution_ack : public ::google::protobuf::Message {
 public:
  execution_ack();
  virtual ~execution_ack();

  execution_ack(const execution_ack& from);

  inline execution_ack& operator=(const execution_ack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const execution_ack& default_instance();

  void Swap(execution_ack* other);

  // implements Message ----------------------------------------------

  execution_ack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const execution_ack& from);
  void MergeFrom(const execution_ack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes order_id = 1;
  inline bool has_order_id() const;
  inline void clear_order_id();
  static const int kOrderIdFieldNumber = 1;
  inline const ::std::string& order_id() const;
  inline void set_order_id(const ::std::string& value);
  inline void set_order_id(const char* value);
  inline void set_order_id(const void* value, size_t size);
  inline ::std::string* mutable_order_id();
  inline ::std::string* release_order_id();
  inline void set_allocated_order_id(::std::string* order_id);

  // optional bytes cl_order_id = 2;
  inline bool has_cl_order_id() const;
  inline void clear_cl_order_id();
  static const int kClOrderIdFieldNumber = 2;
  inline const ::std::string& cl_order_id() const;
  inline void set_cl_order_id(const ::std::string& value);
  inline void set_cl_order_id(const char* value);
  inline void set_cl_order_id(const void* value, size_t size);
  inline ::std::string* mutable_cl_order_id();
  inline ::std::string* release_cl_order_id();
  inline void set_allocated_cl_order_id(::std::string* cl_order_id);

  // optional sfixed32 exec_ack_status = 3;
  inline bool has_exec_ack_status() const;
  inline void clear_exec_ack_status();
  static const int kExecAckStatusFieldNumber = 3;
  inline ::google::protobuf::int32 exec_ack_status() const;
  inline void set_exec_ack_status(::google::protobuf::int32 value);

  // optional bytes exec_id = 4;
  inline bool has_exec_id() const;
  inline void clear_exec_id();
  static const int kExecIdFieldNumber = 4;
  inline const ::std::string& exec_id() const;
  inline void set_exec_id(const ::std::string& value);
  inline void set_exec_id(const char* value);
  inline void set_exec_id(const void* value, size_t size);
  inline ::std::string* mutable_exec_id();
  inline ::std::string* release_exec_id();
  inline void set_allocated_exec_id(::std::string* exec_id);

  // optional string symbol = 5;
  inline bool has_symbol() const;
  inline void clear_symbol();
  static const int kSymbolFieldNumber = 5;
  inline const ::std::string& symbol() const;
  inline void set_symbol(const ::std::string& value);
  inline void set_symbol(const char* value);
  inline void set_symbol(const char* value, size_t size);
  inline ::std::string* mutable_symbol();
  inline ::std::string* release_symbol();
  inline void set_allocated_symbol(::std::string* symbol);

  // optional string fut_sett_date = 6;
  inline bool has_fut_sett_date() const;
  inline void clear_fut_sett_date();
  static const int kFutSettDateFieldNumber = 6;
  inline const ::std::string& fut_sett_date() const;
  inline void set_fut_sett_date(const ::std::string& value);
  inline void set_fut_sett_date(const char* value);
  inline void set_fut_sett_date(const char* value, size_t size);
  inline ::std::string* mutable_fut_sett_date();
  inline ::std::string* release_fut_sett_date();
  inline void set_allocated_fut_sett_date(::std::string* fut_sett_date);

  // optional .capkproto.side_t side = 7;
  inline bool has_side() const;
  inline void clear_side();
  static const int kSideFieldNumber = 7;
  inline ::capkproto::side_t side() const;
  inline void set_side(::capkproto::side_t value);

  // optional double order_qty = 8;
  inline bool has_order_qty() const;
  inline void clear_order_qty();
  static const int kOrderQtyFieldNumber = 8;
  inline double order_qty() const;
  inline void set_order_qty(double value);

  // optional double last_qty = 9;
  inline bool has_last_qty() const;
  inline void clear_last_qty();
  static const int kLastQtyFieldNumber = 9;
  inline double last_qty() const;
  inline void set_last_qty(double value);

  // optional double last_price = 10;
  inline bool has_last_price() const;
  inline void clear_last_price();
  static const int kLastPriceFieldNumber = 10;
  inline double last_price() const;
  inline void set_last_price(double value);

  // optional double cum_qty = 11;
  inline bool has_cum_qty() const;
  inline void clear_cum_qty();
  static const int kCumQtyFieldNumber = 11;
  inline double cum_qty() const;
  inline void set_cum_qty(double value);

  // optional double last_spot_rate = 12;
  inline bool has_last_spot_rate() const;
  inline void clear_last_spot_rate();
  static const int kLastSpotRateFieldNumber = 12;
  inline double last_spot_rate() const;
  inline void set_last_spot_rate(double value);

  // @@protoc_insertion_point(class_scope:capkproto.execution_ack)
 private:
  inline void set_has_order_id();
  inline void clear_has_order_id();
  inline void set_has_cl_order_id();
  inline void clear_has_cl_order_id();
  inline void set_has_exec_ack_status();
  inline void clear_has_exec_ack_status();
  inline void set_has_exec_id();
  inline void clear_has_exec_id();
  inline void set_has_symbol();
  inline void clear_has_symbol();
  inline void set_has_fut_sett_date();
  inline void clear_has_fut_sett_date();
  inline void set_has_side();
  inline void clear_has_side();
  inline void set_has_order_qty();
  inline void clear_has_order_qty();
  inline void set_has_last_qty();
  inline void clear_has_last_qty();
  inline void set_has_last_price();
  inline void clear_has_last_price();
  inline void set_has_cum_qty();
  inline void clear_has_cum_qty();
  inline void set_has_last_spot_rate();
  inline void clear_has_last_spot_rate();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* order_id_;
  ::std::string* cl_order_id_;
  ::std::string* exec_id_;
  ::std::string* symbol_;
  ::google::protobuf::int32 exec_ack_status_;
  int side_;
  ::std::string* fut_sett_date_;
  double order_qty_;
  double last_qty_;
  double last_price_;
  double cum_qty_;
  double last_spot_rate_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(12 + 31) / 32];

  friend void  protobuf_AddDesc_execution_5fack_2eproto();
  friend void protobuf_AssignDesc_execution_5fack_2eproto();
  friend void protobuf_ShutdownFile_execution_5fack_2eproto();

  void InitAsDefaultInstance();
  static execution_ack* default_instance_;
};
// ===================================================================


// ===================================================================

// execution_ack

// optional bytes order_id = 1;
inline bool execution_ack::has_order_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void execution_ack::set_has_order_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void execution_ack::clear_has_order_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void execution_ack::clear_order_id() {
  if (order_id_ != &::google::protobuf::internal::kEmptyString) {
    order_id_->clear();
  }
  clear_has_order_id();
}
inline const ::std::string& execution_ack::order_id() const {
  return *order_id_;
}
inline void execution_ack::set_order_id(const ::std::string& value) {
  set_has_order_id();
  if (order_id_ == &::google::protobuf::internal::kEmptyString) {
    order_id_ = new ::std::string;
  }
  order_id_->assign(value);
}
inline void execution_ack::set_order_id(const char* value) {
  set_has_order_id();
  if (order_id_ == &::google::protobuf::internal::kEmptyString) {
    order_id_ = new ::std::string;
  }
  order_id_->assign(value);
}
inline void execution_ack::set_order_id(const void* value, size_t size) {
  set_has_order_id();
  if (order_id_ == &::google::protobuf::internal::kEmptyString) {
    order_id_ = new ::std::string;
  }
  order_id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* execution_ack::mutable_order_id() {
  set_has_order_id();
  if (order_id_ == &::google::protobuf::internal::kEmptyString) {
    order_id_ = new ::std::string;
  }
  return order_id_;
}
inline ::std::string* execution_ack::release_order_id() {
  clear_has_order_id();
  if (order_id_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = order_id_;
    order_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void execution_ack::set_allocated_order_id(::std::string* order_id) {
  if (order_id_ != &::google::protobuf::internal::kEmptyString) {
    delete order_id_;
  }
  if (order_id) {
    set_has_order_id();
    order_id_ = order_id;
  } else {
    clear_has_order_id();
    order_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bytes cl_order_id = 2;
inline bool execution_ack::has_cl_order_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void execution_ack::set_has_cl_order_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void execution_ack::clear_has_cl_order_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void execution_ack::clear_cl_order_id() {
  if (cl_order_id_ != &::google::protobuf::internal::kEmptyString) {
    cl_order_id_->clear();
  }
  clear_has_cl_order_id();
}
inline const ::std::string& execution_ack::cl_order_id() const {
  return *cl_order_id_;
}
inline void execution_ack::set_cl_order_id(const ::std::string& value) {
  set_has_cl_order_id();
  if (cl_order_id_ == &::google::protobuf::internal::kEmptyString) {
    cl_order_id_ = new ::std::string;
  }
  cl_order_id_->assign(value);
}
inline void execution_ack::set_cl_order_id(const char* value) {
  set_has_cl_order_id();
  if (cl_order_id_ == &::google::protobuf::internal::kEmptyString) {
    cl_order_id_ = new ::std::string;
  }
  cl_order_id_->assign(value);
}
inline void execution_ack::set_cl_order_id(const void* value, size_t size) {
  set_has_cl_order_id();
  if (cl_order_id_ == &::google::protobuf::internal::kEmptyString) {
    cl_order_id_ = new ::std::string;
  }
  cl_order_id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* execution_ack::mutable_cl_order_id() {
  set_has_cl_order_id();
  if (cl_order_id_ == &::google::protobuf::internal::kEmptyString) {
    cl_order_id_ = new ::std::string;
  }
  return cl_order_id_;
}
inline ::std::string* execution_ack::release_cl_order_id() {
  clear_has_cl_order_id();
  if (cl_order_id_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = cl_order_id_;
    cl_order_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void execution_ack::set_allocated_cl_order_id(::std::string* cl_order_id) {
  if (cl_order_id_ != &::google::protobuf::internal::kEmptyString) {
    delete cl_order_id_;
  }
  if (cl_order_id) {
    set_has_cl_order_id();
    cl_order_id_ = cl_order_id;
  } else {
    clear_has_cl_order_id();
    cl_order_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional sfixed32 exec_ack_status = 3;
inline bool execution_ack::has_exec_ack_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void execution_ack::set_has_exec_ack_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void execution_ack::clear_has_exec_ack_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void execution_ack::clear_exec_ack_status() {
  exec_ack_status_ = 0;
  clear_has_exec_ack_status();
}
inline ::google::protobuf::int32 execution_ack::exec_ack_status() const {
  return exec_ack_status_;
}
inline void execution_ack::set_exec_ack_status(::google::protobuf::int32 value) {
  set_has_exec_ack_status();
  exec_ack_status_ = value;
}

// optional bytes exec_id = 4;
inline bool execution_ack::has_exec_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void execution_ack::set_has_exec_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void execution_ack::clear_has_exec_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void execution_ack::clear_exec_id() {
  if (exec_id_ != &::google::protobuf::internal::kEmptyString) {
    exec_id_->clear();
  }
  clear_has_exec_id();
}
inline const ::std::string& execution_ack::exec_id() const {
  return *exec_id_;
}
inline void execution_ack::set_exec_id(const ::std::string& value) {
  set_has_exec_id();
  if (exec_id_ == &::google::protobuf::internal::kEmptyString) {
    exec_id_ = new ::std::string;
  }
  exec_id_->assign(value);
}
inline void execution_ack::set_exec_id(const char* value) {
  set_has_exec_id();
  if (exec_id_ == &::google::protobuf::internal::kEmptyString) {
    exec_id_ = new ::std::string;
  }
  exec_id_->assign(value);
}
inline void execution_ack::set_exec_id(const void* value, size_t size) {
  set_has_exec_id();
  if (exec_id_ == &::google::protobuf::internal::kEmptyString) {
    exec_id_ = new ::std::string;
  }
  exec_id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* execution_ack::mutable_exec_id() {
  set_has_exec_id();
  if (exec_id_ == &::google::protobuf::internal::kEmptyString) {
    exec_id_ = new ::std::string;
  }
  return exec_id_;
}
inline ::std::string* execution_ack::release_exec_id() {
  clear_has_exec_id();
  if (exec_id_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = exec_id_;
    exec_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void execution_ack::set_allocated_exec_id(::std::string* exec_id) {
  if (exec_id_ != &::google::protobuf::internal::kEmptyString) {
    delete exec_id_;
  }
  if (exec_id) {
    set_has_exec_id();
    exec_id_ = exec_id;
  } else {
    clear_has_exec_id();
    exec_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string symbol = 5;
inline bool execution_ack::has_symbol() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void execution_ack::set_has_symbol() {
  _has_bits_[0] |= 0x00000010u;
}
inline void execution_ack::clear_has_symbol() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void execution_ack::clear_symbol() {
  if (symbol_ != &::google::protobuf::internal::kEmptyString) {
    symbol_->clear();
  }
  clear_has_symbol();
}
inline const ::std::string& execution_ack::symbol() const {
  return *symbol_;
}
inline void execution_ack::set_symbol(const ::std::string& value) {
  set_has_symbol();
  if (symbol_ == &::google::protobuf::internal::kEmptyString) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(value);
}
inline void execution_ack::set_symbol(const char* value) {
  set_has_symbol();
  if (symbol_ == &::google::protobuf::internal::kEmptyString) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(value);
}
inline void execution_ack::set_symbol(const char* value, size_t size) {
  set_has_symbol();
  if (symbol_ == &::google::protobuf::internal::kEmptyString) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* execution_ack::mutable_symbol() {
  set_has_symbol();
  if (symbol_ == &::google::protobuf::internal::kEmptyString) {
    symbol_ = new ::std::string;
  }
  return symbol_;
}
inline ::std::string* execution_ack::release_symbol() {
  clear_has_symbol();
  if (symbol_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = symbol_;
    symbol_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void execution_ack::set_allocated_symbol(::std::string* symbol) {
  if (symbol_ != &::google::protobuf::internal::kEmptyString) {
    delete symbol_;
  }
  if (symbol) {
    set_has_symbol();
    symbol_ = symbol;
  } else {
    clear_has_symbol();
    symbol_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string fut_sett_date = 6;
inline bool execution_ack::has_fut_sett_date() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void execution_ack::set_has_fut_sett_date() {
  _has_bits_[0] |= 0x00000020u;
}
inline void execution_ack::clear_has_fut_sett_date() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void execution_ack::clear_fut_sett_date() {
  if (fut_sett_date_ != &::google::protobuf::internal::kEmptyString) {
    fut_sett_date_->clear();
  }
  clear_has_fut_sett_date();
}
inline const ::std::string& execution_ack::fut_sett_date() const {
  return *fut_sett_date_;
}
inline void execution_ack::set_fut_sett_date(const ::std::string& value) {
  set_has_fut_sett_date();
  if (fut_sett_date_ == &::google::protobuf::internal::kEmptyString) {
    fut_sett_date_ = new ::std::string;
  }
  fut_sett_date_->assign(value);
}
inline void execution_ack::set_fut_sett_date(const char* value) {
  set_has_fut_sett_date();
  if (fut_sett_date_ == &::google::protobuf::internal::kEmptyString) {
    fut_sett_date_ = new ::std::string;
  }
  fut_sett_date_->assign(value);
}
inline void execution_ack::set_fut_sett_date(const char* value, size_t size) {
  set_has_fut_sett_date();
  if (fut_sett_date_ == &::google::protobuf::internal::kEmptyString) {
    fut_sett_date_ = new ::std::string;
  }
  fut_sett_date_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* execution_ack::mutable_fut_sett_date() {
  set_has_fut_sett_date();
  if (fut_sett_date_ == &::google::protobuf::internal::kEmptyString) {
    fut_sett_date_ = new ::std::string;
  }
  return fut_sett_date_;
}
inline ::std::string* execution_ack::release_fut_sett_date() {
  clear_has_fut_sett_date();
  if (fut_sett_date_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = fut_sett_date_;
    fut_sett_date_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void execution_ack::set_allocated_fut_sett_date(::std::string* fut_sett_date) {
  if (fut_sett_date_ != &::google::protobuf::internal::kEmptyString) {
    delete fut_sett_date_;
  }
  if (fut_sett_date) {
    set_has_fut_sett_date();
    fut_sett_date_ = fut_sett_date;
  } else {
    clear_has_fut_sett_date();
    fut_sett_date_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .capkproto.side_t side = 7;
inline bool execution_ack::has_side() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void execution_ack::set_has_side() {
  _has_bits_[0] |= 0x00000040u;
}
inline void execution_ack::clear_has_side() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void execution_ack::clear_side() {
  side_ = 1;
  clear_has_side();
}
inline ::capkproto::side_t execution_ack::side() const {
  return static_cast< ::capkproto::side_t >(side_);
}
inline void execution_ack::set_side(::capkproto::side_t value) {
  assert(::capkproto::side_t_IsValid(value));
  set_has_side();
  side_ = value;
}

// optional double order_qty = 8;
inline bool execution_ack::has_order_qty() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void execution_ack::set_has_order_qty() {
  _has_bits_[0] |= 0x00000080u;
}
inline void execution_ack::clear_has_order_qty() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void execution_ack::clear_order_qty() {
  order_qty_ = 0;
  clear_has_order_qty();
}
inline double execution_ack::order_qty() const {
  return order_qty_;
}
inline void execution_ack::set_order_qty(double value) {
  set_has_order_qty();
  order_qty_ = value;
}

// optional double last_qty = 9;
inline bool execution_ack::has_last_qty() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void execution_ack::set_has_last_qty() {
  _has_bits_[0] |= 0x00000100u;
}
inline void execution_ack::clear_has_last_qty() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void execution_ack::clear_last_qty() {
  last_qty_ = 0;
  clear_has_last_qty();
}
inline double execution_ack::last_qty() const {
  return last_qty_;
}
inline void execution_ack::set_last_qty(double value) {
  set_has_last_qty();
  last_qty_ = value;
}

// optional double last_price = 10;
inline bool execution_ack::has_last_price() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void execution_ack::set_has_last_price() {
  _has_bits_[0] |= 0x00000200u;
}
inline void execution_ack::clear_has_last_price() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void execution_ack::clear_last_price() {
  last_price_ = 0;
  clear_has_last_price();
}
inline double execution_ack::last_price() const {
  return last_price_;
}
inline void execution_ack::set_last_price(double value) {
  set_has_last_price();
  last_price_ = value;
}

// optional double cum_qty = 11;
inline bool execution_ack::has_cum_qty() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void execution_ack::set_has_cum_qty() {
  _has_bits_[0] |= 0x00000400u;
}
inline void execution_ack::clear_has_cum_qty() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void execution_ack::clear_cum_qty() {
  cum_qty_ = 0;
  clear_has_cum_qty();
}
inline double execution_ack::cum_qty() const {
  return cum_qty_;
}
inline void execution_ack::set_cum_qty(double value) {
  set_has_cum_qty();
  cum_qty_ = value;
}

// optional double last_spot_rate = 12;
inline bool execution_ack::has_last_spot_rate() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void execution_ack::set_has_last_spot_rate() {
  _has_bits_[0] |= 0x00000800u;
}
inline void execution_ack::clear_has_last_spot_rate() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void execution_ack::clear_last_spot_rate() {
  last_spot_rate_ = 0;
  clear_has_last_spot_rate();
}
inline double execution_ack::last_spot_rate() const {
  return last_spot_rate_;
}
inline void execution_ack::set_last_spot_rate(double value) {
  set_has_last_spot_rate();
  last_spot_rate_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace capkproto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_execution_5fack_2eproto__INCLUDED
