# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heartbeat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import capk_globals_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='heartbeat.proto',
  package='capkproto',
  serialized_pb='\n\x0fheartbeat.proto\x12\tcapkproto\x1a\x12\x63\x61pk_globals.proto\"\x1c\n\x08hearbeat\x12\x10\n\x08venue_id\x18\x01 \x02(\x0f')




_HEARBEAT = _descriptor.Descriptor(
  name='hearbeat',
  full_name='capkproto.hearbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='venue_id', full_name='capkproto.hearbeat.venue_id', index=0,
      number=1, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['hearbeat'] = _HEARBEAT

class hearbeat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEARBEAT

  # @@protoc_insertion_point(class_scope:capkproto.hearbeat)


# @@protoc_insertion_point(module_scope)
