# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interactive_brokers.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import capk_globals_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='interactive_brokers.proto',
  package='capkproto',
  serialized_pb='\n\x19interactive_brokers.proto\x12\tcapkproto\x1a\x12\x63\x61pk_globals.proto\"\x85\x01\n\x17interactive_brokers_bbo\x12\x10\n\x08venue_id\x18\x01 \x02(\x0f\x12\x0e\n\x06symbol\x18\x02 \x02(\t\x12\x10\n\x08\x62id_size\x18\x03 \x02(\x01\x12\x11\n\tbid_price\x18\x04 \x02(\x01\x12\x10\n\x08\x61sk_size\x18\x05 \x02(\x01\x12\x11\n\task_price\x18\x06 \x02(\x01\"\x9d\x02\n\x1cinteractive_brokers_contract\x12\r\n\x05\x63onId\x18\x01 \x02(\x0f\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0f\n\x07secType\x18\x03 \x01(\t\x12\x0e\n\x06\x65xpiry\x18\x04 \x01(\t\x12\x0e\n\x06strike\x18\x05 \x01(\x01\x12\r\n\x05right\x18\x06 \x01(\t\x12\x12\n\nmultiplier\x18\x07 \x01(\t\x12\x10\n\x08\x65xchange\x18\x08 \x01(\t\x12\x17\n\x0fprimaryExchagne\x18\t \x01(\t\x12\x10\n\x08\x63urrency\x18\n \x01(\t\x12\x13\n\x0blocalSymbol\x18\x0b \x01(\t\x12\x16\n\x0eincludeExpired\x18\x0c \x01(\x08\x12\x11\n\tsecIdType\x18\r \x01(\t\x12\r\n\x05secId\x18\x0e \x01(\t')




_INTERACTIVE_BROKERS_BBO = _descriptor.Descriptor(
  name='interactive_brokers_bbo',
  full_name='capkproto.interactive_brokers_bbo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='venue_id', full_name='capkproto.interactive_brokers_bbo.venue_id', index=0,
      number=1, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='capkproto.interactive_brokers_bbo.symbol', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bid_size', full_name='capkproto.interactive_brokers_bbo.bid_size', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bid_price', full_name='capkproto.interactive_brokers_bbo.bid_price', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ask_size', full_name='capkproto.interactive_brokers_bbo.ask_size', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ask_price', full_name='capkproto.interactive_brokers_bbo.ask_price', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=194,
)


_INTERACTIVE_BROKERS_CONTRACT = _descriptor.Descriptor(
  name='interactive_brokers_contract',
  full_name='capkproto.interactive_brokers_contract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conId', full_name='capkproto.interactive_brokers_contract.conId', index=0,
      number=1, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='capkproto.interactive_brokers_contract.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secType', full_name='capkproto.interactive_brokers_contract.secType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='capkproto.interactive_brokers_contract.expiry', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strike', full_name='capkproto.interactive_brokers_contract.strike', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right', full_name='capkproto.interactive_brokers_contract.right', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='capkproto.interactive_brokers_contract.multiplier', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='capkproto.interactive_brokers_contract.exchange', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='primaryExchagne', full_name='capkproto.interactive_brokers_contract.primaryExchagne', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='capkproto.interactive_brokers_contract.currency', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='localSymbol', full_name='capkproto.interactive_brokers_contract.localSymbol', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='includeExpired', full_name='capkproto.interactive_brokers_contract.includeExpired', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secIdType', full_name='capkproto.interactive_brokers_contract.secIdType', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secId', full_name='capkproto.interactive_brokers_contract.secId', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=197,
  serialized_end=482,
)

DESCRIPTOR.message_types_by_name['interactive_brokers_bbo'] = _INTERACTIVE_BROKERS_BBO
DESCRIPTOR.message_types_by_name['interactive_brokers_contract'] = _INTERACTIVE_BROKERS_CONTRACT

class interactive_brokers_bbo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTERACTIVE_BROKERS_BBO

  # @@protoc_insertion_point(class_scope:capkproto.interactive_brokers_bbo)

class interactive_brokers_contract(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTERACTIVE_BROKERS_CONTRACT

  # @@protoc_insertion_point(class_scope:capkproto.interactive_brokers_contract)


# @@protoc_insertion_point(module_scope)
