# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import capk_globals_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='order_status.proto',
  package='capkproto',
  serialized_pb='\n\x12order_status.proto\x12\tcapkproto\x1a\x12\x63\x61pk_globals.proto\"\x92\x01\n\x0corder_status\x12\x10\n\x08order_id\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63l_order_id\x18\x02 \x01(\x0c\x12\x13\n\x0bstrategy_id\x18\x03 \x01(\x0c\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x1f\n\x04side\x18\x05 \x01(\x0e\x32\x11.capkproto.side_t\x12\x15\n\rsecurity_type\x18\x06 \x01(\t\"\xfa\x01\n\x0fgroup_no_orders\x12\x13\n\x0b\x63l_order_id\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63um_qty\x18\x02 \x01(\x01\x12\x12\n\nord_status\x18\x03 \x01(\x0f\x12\x12\n\nleaves_qty\x18\x04 \x01(\x01\x12\x0f\n\x07\x63xl_qty\x18\x05 \x01(\x01\x12\x15\n\rtime_in_force\x18\x06 \x01(\x0f\x12\x0e\n\x06\x61vg_px\x18\x07 \x01(\x01\x12\x0c\n\x04text\x18\x08 \x01(\t\x12\x10\n\x08order_id\x18\t \x01(\t\x12\x0e\n\x06symbol\x18\n \x01(\t\x12\x1f\n\x04side\x18\x0b \x01(\x0e\x32\x11.capkproto.side_t\x12\x10\n\x08ord_type\x18\x0c \x01(\x0f\"\xd1\x01\n\x0blist_status\x12\x0f\n\x07list_id\x18\x01 \x01(\t\x12\x18\n\x10list_status_type\x18\x02 \x01(\x0f\x12\x0f\n\x07no_rpts\x18\x03 \x01(\x0f\x12\x19\n\x11list_order_status\x18\x04 \x01(\x0f\x12\x0f\n\x07rpt_seq\x18\x05 \x01(\x0f\x12\x0c\n\x04text\x18\x06 \x01(\t\x12\x15\n\rtot_no_orders\x18\x07 \x01(\x0f\x12\x35\n\x11order_status_list\x18\t \x03(\x0b\x32\x1a.capkproto.group_no_orders')




_ORDER_STATUS = _descriptor.Descriptor(
  name='order_status',
  full_name='capkproto.order_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='capkproto.order_status.order_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cl_order_id', full_name='capkproto.order_status.cl_order_id', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strategy_id', full_name='capkproto.order_status.strategy_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='capkproto.order_status.symbol', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='side', full_name='capkproto.order_status.side', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='security_type', full_name='capkproto.order_status.security_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=200,
)


_GROUP_NO_ORDERS = _descriptor.Descriptor(
  name='group_no_orders',
  full_name='capkproto.group_no_orders',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cl_order_id', full_name='capkproto.group_no_orders.cl_order_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cum_qty', full_name='capkproto.group_no_orders.cum_qty', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ord_status', full_name='capkproto.group_no_orders.ord_status', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leaves_qty', full_name='capkproto.group_no_orders.leaves_qty', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cxl_qty', full_name='capkproto.group_no_orders.cxl_qty', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_in_force', full_name='capkproto.group_no_orders.time_in_force', index=5,
      number=6, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_px', full_name='capkproto.group_no_orders.avg_px', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='capkproto.group_no_orders.text', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='capkproto.group_no_orders.order_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='capkproto.group_no_orders.symbol', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='side', full_name='capkproto.group_no_orders.side', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ord_type', full_name='capkproto.group_no_orders.ord_type', index=11,
      number=12, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=203,
  serialized_end=453,
)


_LIST_STATUS = _descriptor.Descriptor(
  name='list_status',
  full_name='capkproto.list_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list_id', full_name='capkproto.list_status.list_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_status_type', full_name='capkproto.list_status.list_status_type', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_rpts', full_name='capkproto.list_status.no_rpts', index=2,
      number=3, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_order_status', full_name='capkproto.list_status.list_order_status', index=3,
      number=4, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpt_seq', full_name='capkproto.list_status.rpt_seq', index=4,
      number=5, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='capkproto.list_status.text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tot_no_orders', full_name='capkproto.list_status.tot_no_orders', index=6,
      number=7, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order_status_list', full_name='capkproto.list_status.order_status_list', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=456,
  serialized_end=665,
)

_ORDER_STATUS.fields_by_name['side'].enum_type = capk_globals_pb2._SIDE_T
_GROUP_NO_ORDERS.fields_by_name['side'].enum_type = capk_globals_pb2._SIDE_T
_LIST_STATUS.fields_by_name['order_status_list'].message_type = _GROUP_NO_ORDERS
DESCRIPTOR.message_types_by_name['order_status'] = _ORDER_STATUS
DESCRIPTOR.message_types_by_name['group_no_orders'] = _GROUP_NO_ORDERS
DESCRIPTOR.message_types_by_name['list_status'] = _LIST_STATUS

class order_status(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDER_STATUS

  # @@protoc_insertion_point(class_scope:capkproto.order_status)

class group_no_orders(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GROUP_NO_ORDERS

  # @@protoc_insertion_point(class_scope:capkproto.group_no_orders)

class list_status(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LIST_STATUS

  # @@protoc_insertion_point(class_scope:capkproto.list_status)


# @@protoc_insertion_point(module_scope)
