# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import capk_globals_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='order_cancel.proto',
  package='capkproto',
  serialized_pb='\n\x12order_cancel.proto\x12\tcapkproto\x1a\x12\x63\x61pk_globals.proto\"\xaa\x01\n\x0corder_cancel\x12\x15\n\rorig_order_id\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63l_order_id\x18\x02 \x01(\x0c\x12\x13\n\x0bstrategy_id\x18\x03 \x01(\x0c\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x1f\n\x04side\x18\x05 \x01(\x0e\x32\x11.capkproto.side_t\x12\x11\n\torder_qty\x18\x06 \x01(\x01\x12\x15\n\rfut_sett_date\x18\x07 \x01(\t')




_ORDER_CANCEL = descriptor.Descriptor(
  name='order_cancel',
  full_name='capkproto.order_cancel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='orig_order_id', full_name='capkproto.order_cancel.orig_order_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cl_order_id', full_name='capkproto.order_cancel.cl_order_id', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='strategy_id', full_name='capkproto.order_cancel.strategy_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='symbol', full_name='capkproto.order_cancel.symbol', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='side', full_name='capkproto.order_cancel.side', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='order_qty', full_name='capkproto.order_cancel.order_qty', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fut_sett_date', full_name='capkproto.order_cancel.fut_sett_date', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=224,
)

_ORDER_CANCEL.fields_by_name['side'].enum_type = capk_globals_pb2._SIDE_T
DESCRIPTOR.message_types_by_name['order_cancel'] = _ORDER_CANCEL

class order_cancel(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDER_CANCEL
  
  # @@protoc_insertion_point(class_scope:capkproto.order_cancel)

# @@protoc_insertion_point(module_scope)
