# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import capk_globals_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='venue_configuration.proto',
  package='capkproto',
  serialized_pb='\n\x19venue_configuration.proto\x12\tcapkproto\x1a\x12\x63\x61pk_globals.proto\"\'\n\x13venue_configuration\x12\x10\n\x08venue_id\x18\x01 \x01(\t')




_VENUE_CONFIGURATION = descriptor.Descriptor(
  name='venue_configuration',
  full_name='capkproto.venue_configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='venue_id', full_name='capkproto.venue_configuration.venue_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=60,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['venue_configuration'] = _VENUE_CONFIGURATION

class venue_configuration(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VENUE_CONFIGURATION
  
  # @@protoc_insertion_point(class_scope:capkproto.venue_configuration)

# @@protoc_insertion_point(module_scope)
